services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "crypto_db"
    networks:
      - exam-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend-service:
    build:
      context: ./be
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      MYSQL_HOST: "mysqldb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
    ports:
      - "5001:5001"
    networks:
      - exam-net

  web:
    build:
      context: ./fe
    depends_on:
      - backend-service
    ports:
      - "5002:5002"
    networks:
      - exam-net

networks:
  exam-net:
    driver: bridge